name: 'Apt Install Deps'
description: 'Install the packages needed for building and deploying'
runs:
  using: 'composite'
  steps:
    - name: Install Linux build dependencies
      shell: bash
      run: |
        UPDATE_LIB=1 bash ./scripts/linux.d/debian
        sudo chown $USER -R ./
