cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ORCA_MACOS_BUILD_DIR OR ORCA_MACOS_BUILD_DIR STREQUAL "")
    message(FATAL_ERROR "ORCA_MACOS_BUILD_DIR is required")
endif()

foreach(_orca_path_var ORCA_MACOS_BUILD_DIR ORCA_MACOS_STAGE_DIR ORCA_MACOS_CONFIG)
    if(DEFINED ${_orca_path_var})
        string(REGEX REPLACE "^\"|\"$" "" ${_orca_path_var} "${${_orca_path_var}}")
    endif()
endforeach()

if(NOT DEFINED ORCA_MACOS_STAGE_DIR OR ORCA_MACOS_STAGE_DIR STREQUAL "")
    set(ORCA_MACOS_STAGE_DIR "${ORCA_MACOS_BUILD_DIR}/OrcaSlicer")
endif()

set(_config_candidates "")
if(DEFINED ORCA_MACOS_CONFIG AND NOT ORCA_MACOS_CONFIG STREQUAL "")
    list(APPEND _config_candidates "${ORCA_MACOS_CONFIG}")
endif()
list(APPEND _config_candidates "")

function(_orca_find_bundle out_var bundle_name)
    foreach(_cfg IN LISTS _config_candidates)
        if(_cfg STREQUAL "")
            set(_candidate "${ORCA_MACOS_BUILD_DIR}/src/${bundle_name}")
        else()
            set(_candidate "${ORCA_MACOS_BUILD_DIR}/src/${_cfg}/${bundle_name}")
        endif()

        if(EXISTS "${_candidate}")
            set(${out_var} "${_candidate}" PARENT_SCOPE)
            return()
        endif()
    endforeach()

    set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_orca_materialize_resources app_path)
    set(_resources_path "${app_path}/Contents/Resources")
    if(IS_SYMLINK "${_resources_path}")
        file(READ_SYMLINK "${_resources_path}" _resources_target)
        if(NOT IS_ABSOLUTE "${_resources_target}")
            get_filename_component(_resources_parent "${_resources_path}" DIRECTORY)
            get_filename_component(_resources_target "${_resources_parent}/${_resources_target}" ABSOLUTE)
        endif()

        file(REMOVE "${_resources_path}")
        file(MAKE_DIRECTORY "${_resources_path}")
        file(COPY "${_resources_target}/" DESTINATION "${_resources_path}")
    endif()
endfunction()

function(_orca_remove_ds_store root_path)
    file(GLOB_RECURSE _ds_store_files "${root_path}/.DS_Store")
    if(_ds_store_files)
        file(REMOVE ${_ds_store_files})
    endif()
endfunction()

function(_orca_stage_bundle bundle_name required)
    _orca_find_bundle(_source_bundle "${bundle_name}")
    if(_source_bundle STREQUAL "")
        if(required)
            message(FATAL_ERROR "Could not find ${bundle_name} under ${ORCA_MACOS_BUILD_DIR}/src")
        endif()
        return()
    endif()

    file(REMOVE_RECURSE "${ORCA_MACOS_STAGE_DIR}/${bundle_name}")
    file(COPY "${_source_bundle}" DESTINATION "${ORCA_MACOS_STAGE_DIR}")
    _orca_materialize_resources("${ORCA_MACOS_STAGE_DIR}/${bundle_name}")
    _orca_remove_ds_store("${ORCA_MACOS_STAGE_DIR}/${bundle_name}")
    message(STATUS "Staged ${bundle_name} -> ${ORCA_MACOS_STAGE_DIR}/${bundle_name}")
endfunction()

file(MAKE_DIRECTORY "${ORCA_MACOS_STAGE_DIR}")
_orca_stage_bundle("OrcaSlicer.app" TRUE)
_orca_stage_bundle("OrcaSlicer_profile_validator.app" FALSE)
